import { AnalysisStats } from "@/lib/analysis-engine"
import { Card, CardContent, CardFooter, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Download, Share2 } from "lucide-react"

interface SocialCardProps {
    stats: AnalysisStats
    period?: string
}

export function SocialCard({ stats, period = "週間レポート" }: SocialCardProps) {
    return (
        <div className="flex flex-col gap-4 items-center">
            {/* A案: Simple & Professional (MT4-inspired) */}
            <div className="relative w-full max-w-md aspect-[4/5] rounded-sm overflow-hidden shadow-2xl bg-[#1a1a1a] text-white p-8 flex flex-col justify-between border border-[#333]">
                {/* Header with Gold Accent */}
                <div>
                    <div className="flex justify-between items-start border-b border-[#d4af37] pb-3 mb-6">
                        <div>
                            <h3 className="text-xs font-medium text-[#888] uppercase tracking-wider mb-1">SOLO</h3>
                            <h2 className="text-2xl font-bold text-white">{period}</h2>
                        </div>
                        <div className="h-10 w-10 rounded-sm bg-[#d4af37]/20 border border-[#d4af37] flex items-center justify-center">
                            <span className="text-xl">📊</span>
                        </div>
                    </div>
                </div>

                {/* Main Stats - Grid Layout */}
                <div className="grid grid-cols-2 gap-4 my-6">
                    <div className="bg-black/30 rounded-sm p-4 border border-[#333]">
                        <p className="text-xs text-[#888] mb-2">勝率</p>
                        <p className="text-4xl font-bold text-[#ff4444]">{stats.winRate}%</p>
                    </div>
                    <div className="bg-black/30 rounded-sm p-4 border border-[#333]">
                        <p className="text-xs text-[#888] mb-2">PF</p>
                        <p className="text-4xl font-bold text-[#d4af37]">{stats.profitFactor}</p>
                    </div>
                </div>

                {/* Secondary Stats - List */}
                <div className="space-y-3 mb-6">
                    <div className="flex justify-between items-center border-b border-[#333] pb-2">
                        <span className="text-sm text-[#aaa]">合計損益</span>
                        <span className={`font-mono font-bold text-lg ${stats.totalPnl >= 0 ? 'text-[#ff4444]' : 'text-[#4444ff]'}`}>
                            {stats.totalPnl > 0 ? '+' : ''}{stats.totalPnl}
                        </span>
                    </div>
                    <div className="flex justify-between items-center border-b border-[#333] pb-2">
                        <span className="text-sm text-[#aaa]">トレード数</span>
                        <span className="font-mono font-bold text-lg text-white">{stats.totalTrades}</span>
                    </div>
                    <div className="flex justify-between items-center">
                        <span className="text-sm text-[#aaa]">ベスト通貨ペア</span>
                        <span className="font-mono font-bold text-lg text-[#d4af37]">{stats.bestPair}</span>
                    </div>
                </div>

                {/* Footer */}
                <div className="pt-4 border-t border-[#d4af37] flex justify-between items-center">
                    <div>
                        <p className="text-[10px] text-[#666]">{new Date().toLocaleDateString('ja-JP')}</p>
                        <p className="text-[10px] text-[#666]">Generated by AI</p>
                    </div>
                    <div className="text-right">
                        <p className="text-sm font-bold text-[#d4af37]">勝率{stats.winRate}%達成</p>
                    </div>
                </div>
            </div>

            <div className="flex gap-2 w-full max-w-md">
                <Button className="flex-1" variant="outline" onClick={() => alert("画像生成をシミュレーションしました！")}>
                    <Download className="mr-2 h-4 w-4" /> ダウンロード
                </Button>
                <Button className="flex-1" onClick={() => alert("シェアをシミュレーションしました！")}>
                    <Share2 className="mr-2 h-4 w-4" /> シェア
                </Button>
            </div>
        </div>
    )
}
